//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kentico.Xperience.AlgoliaSearch.Pages
{


    public partial class AlgoliaSearch_IndexedContent
    {

        /// <summary>
        /// ugProperties control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMSAdminControls_UI_UniGrid_UniGrid ugProperties;

        /// <summary>
        /// ugIncludedContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMSAdminControls_UI_UniGrid_UniGrid ugIncludedContent;
    }
}
