name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/Kentico.Xperience.Algolia.KX13.csproj
    - name: Build
      run: dotnet build src/Kentico.Xperience.Algolia.KX13.csproj --no-restore
    - name: Test
      run: dotnet test tests/Kentico.Xperience.Algolia.KX13.Tests.csproj --no-build --logger GitHubActions
